AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda creation with IAM User or CFI template'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: 'Lambda Info'
        Parameters:
          - LambdaName

    ParameterLabels:
      LambdaName:
        default: 'Lambda Name'
Resources:

  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-s3-bucket-testlambda
	
Resources:
  TestLambda:
    Type: 'AWS::Lambda::Function'
    Properties: {}
	AWSTemplateFormatVersion: '2010-09-09'
	Transform: 'AWS::Serverless-2016-10-31'
	Resources:
	MyFunction:
	Type: 'AWS::Serverless::Function'
	Properties:
	Handler: com.amazonaws.lambda.demo.HelloWorldLambdaHanlder
	Code:
        S3Bucket: !Ref my-s3-bucket-testlambda
        S3Key: aurora-lambda/aurora-lambda.zip
	CodeUri: s3://mybucket/lambdafunction.zip
